{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Product defects","children":[{"name":"The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.intercept()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","children":[{"name":"An uncaught error was detected outside of a test","uid":"74d9ce743aa2575a","parentUid":"94d5b64f12c317b5e0c59bf59be56717","status":"failed","time":{"start":1699125866997,"stop":1699125867027,"duration":30},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"94d5b64f12c317b5e0c59bf59be56717"},{"name":"Timed out retrying after 4000ms: Expected to find content: 'Hi, I'm Mohammad Abohasan - nwcb' within the element: <div.oxd-sheet.oxd-sheet--rounded.oxd-sheet--white.orangehrm-buzz> but never did.","children":[{"name":"Buzz - The user should be able to add a post","uid":"ec4d30897489cb3b","parentUid":"cb5943ad180f452c2c3f7025de3ebbfd","status":"failed","time":{"start":1699140215732,"stop":1699140229930,"duration":14198},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":4,"retriesStatusChange":true,"parameters":[],"tags":[]}],"uid":"cb5943ad180f452c2c3f7025de3ebbfd"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}]}